In [10]:
from numpy import *
##mainly use ndarray objects

s = array(5)
print(s.shape)
x = s + 3

v = array([1, 2, 3])

##probably will return (3,) since it's a tuple
print(v.shape)

c = array([[1, 2, 3], [2, 3, 4]])
print(c.shape)

##basically the first one is dimension and the second one is the vector size. so in [1, 2, 3], numpy returns in a weird way since
##it doens' understand (3) as a tuple with one item

x = v[1]
print(x)

e = v[1:]
print(e)



()
(3L,)
(2L, 3L)


In [13]:
from numpy import*

##numpy operator

values = array([1, 2, 3, 4, 5])
values_add = values +5
print(values_add)

value_multiply = values * 5
print(value_multiply)

##eleminate variables
c = array([[1, 2, 3], [2, 3, 4]])
c *= 0
print(c)

[ 6  7  8  9 10]
[ 5 10 15 20 25]
[[0 0 0]
 [0 0 0]]


In [14]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# displays the following result:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

a.shape
# displays the following result:
#  (2, 2)

c.shape
# displays the following result:
#  (3, 3)

a + c
# displays the following error:
# ValueError: operands could not be broadcast together with shapes (2,2) (3,3)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [15]:
import numpy as np
##dot product


a = np.array([[1,2],[3,4]])
a
# displays the following result:
# array([[1, 2],
#        [3, 4]])

np.dot(a,a)
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

a.dot(a)  # you can call `dot` directly on the `ndarray`
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

np.matmul(a,a)
# array([[ 7, 10],
#        [15, 22]])

array([[ 7, 10],
       [15, 22]])

In [ ]:
m_t = m.T
m_t[3][1] = 200
m_t
# displays the following result:
# array([[ 1,   5, 9],
#        [ 2,   6, 10],
#        [ 3,   7, 11],
#        [ 4, 200, 12]])

m
# displays the following result:
# array([[ 1,  2,  3,   4],
#        [ 5,  6,  7, 200],
#        [ 9, 10, 11,  12]])